name: stock_manager
description: Gestion de stock - Materiaux de construction
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.0.1
  badges: ^3.1.2
  pdf: ^3.10.8
  printing: ^5.12.0
  share_plus: ^7.2.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
